### ISSUE TITLE
Where is circuit schematics located?

### ISSUE THREAD

**Issue by lauritk** [LibreDAQ/libredaq#1]
Hi, I could not find the circuit schematics?

**Comment by jlblancoc** [comment]
I will look for them and upload to this Repository!

**Comment by jlblancoc** [comment]
Done with 13cf9a46abd8d8e9bc6f9743a4fd8047ac413fd7. 
Schematics have been released under Creative Commons Attribution-NonCommercial-ShareAlike license.

Feel free of contributing back any improvement!

Cheers.

**Comment by lauritk** [comment]
Thank you! I will contribute improvements, if any :)
